DEVICE_PATH := device/samsung/a21s

# Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 := 
TARGET_CPU_VARIANT := generic
TARGET_CPU_VARIANT_RUNTIME := generic

# 64 Bit
TARGET_USES_64_BIT_BINDER := true
TARGET_SUPPORTS_64_BIT_APPS := true

# Kernel - prebuilt
TARGET_FORCE_PREBUILT_KERNEL := true
TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilt/kernel
TARGET_PREBUILT_DTB := $(DEVICE_PATH)/prebuilt/dtb.img
BOARD_PREBUILT_DTBOIMAGE := $(DEVICE_PATH)/prebuilt/dtbo.img
BOARD_MKBOOTIMG_ARGS += --dtb $(TARGET_PREBUILT_DTB)

# Partitions
BOARD_SYSTEMIMAGE_PARTITION_TYPE := ext4
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
TARGET_COPY_OUT_VENDOR := vendor

# Properties
TARGET_SYSTEM_PROP += $(DEVICE_PATH)/system.prop

# Filesystems
TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/recovery.fstab

# Screen
TARGET_RECOVERY_PIXEL_FORMAT := "BGRX_8888"
TW_BRIGHTNESS_PATH := "/sys/class/backlight/panel/brightness"
TW_MAX_BRIGHTNESS := 400
TW_DEFAULT_BRIGHTNESS := 200
TW_THEME := portrait_hdpi
TW_FRAMERATE := 60
TARGET_SCREEN_WIDTH := 1080
TARGET_SCREEN_HEIGHT := 2408

# Status Bar UI
TW_STATUS_ICONS_ALIGN := center
TW_CUSTOM_CPU_POS := "150"
TW_CUSTOM_CLOCK_POS := "500"
TW_CUSTOM_BATTERY_POS := "825"
# Version
TW_DEVICE_VERSION := SavedByLight a21s

# Inherit from common tree
include device/samsung/universal3830-common/BoardConfigCommon.mk